# Generated by Django 3.2.9 on 2022-11-24 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre_id', models.IntegerField()),
                ('genre_name', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('keyword_id', models.IntegerField()),
                ('keyword', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'keyword',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('release_date', models.DateField(auto_now_add=True, null=True)),
                ('vote_average', models.FloatField()),
                ('movie_key', models.IntegerField()),
                ('video_path', models.CharField(max_length=1000)),
                ('poster', models.CharField(max_length=1000)),
                ('genres', models.ManyToManyField(to='movies.Genre')),
                ('keyword', models.ManyToManyField(to='movies.Keyword')),
                ('movie_like_user', models.ManyToManyField(related_name='like_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Movie_Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=1000)),
                ('movie_id', models.IntegerField()),
            ],
            options={
                'db_table': 'movie_image',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('review_like_user', models.ManyToManyField(related_name='like_reviews', to=settings.AUTH_USER_MODEL)),
                ('write_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
